version: '3.8'

services:
  maccabi-scraper:
    build: .
    container_name: maccabi-android-scraper
    privileged: true
    environment:
      # Emulator settings
      - DEVICE=Samsung Galaxy S10e
      - API_LEVEL=30
      - TARGET=google_apis
      - ABI=arm64-v8a
      - TAG=google_apis
      # Display settings for headless operation
      - DISPLAY=:99
      - QT_X11_NO_MITSHM=1
      # Performance settings
      - KVM=true
      - EMULATOR_TIMEOUT=300
      - ADB_TIMEOUT=300
    ports:
      - "5037:5037"  # ADB
      - "5554:5554"  # Emulator console
      - "5555:5555"  # Emulator ADB
      - "6080:6080"  # noVNC web interface (if available)
    volumes:
      # Persist AVD data
      - avd_data:/opt/android/avd
      # Mount output directory for results
      - ./output:/app/output
      # Mount logs
      - ./logs:/app/logs
    devices:
      - /dev/kvm:/dev/kvm  # For hardware acceleration (Linux only)
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    command: >
      bash -c "
        echo 'Starting Android emulator for Maccabi scraper...' &&
        # Create AVD if it doesn't exist
        if [ ! -d '/opt/android/avd/maccabi_scraper_avd.avd' ]; then
          echo 'Creating AVD...'
          echo 'no' | avdmanager create avd -n maccabi_scraper_avd -k 'system-images;android-30;google_apis;arm64-v8a' --force
        fi &&
        # Start emulator in background
        emulator -avd maccabi_scraper_avd -no-audio -no-window -gpu swiftshader_indirect -no-snapshot -wipe-data &
        # Wait for emulator to be ready
        adb wait-for-device &&
        echo 'Emulator is ready!' &&
        # Keep container running
        tail -f /dev/null
      "

volumes:
  avd_data:
    driver: local
